Imported Upstream version 1.35

diff --git a/extensions/ipset-6/Makefile.in b/extensions/ipset-6/Makefile.in
--- a/extensions/ipset-6/Makefile.in
+++ b/extensions/ipset-6/Makefile.in
@@ -40,10 +40,10 @@ PRE_UNINSTALL = :
 POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
-DIST_COMMON = $(srcdir)/../../Makefile.extra $(srcdir)/Makefile.am \
-	$(srcdir)/Makefile.in
-sbin_PROGRAMS = iptaccount$(EXEEXT)
-subdir = extensions/ACCOUNT
+DIST_COMMON = README $(srcdir)/../../Makefile.extra \
+	$(srcdir)/Makefile.am $(srcdir)/Makefile.in
+sbin_PROGRAMS = ipset$(EXEEXT)
+subdir = extensions/ipset-6
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
 	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
@@ -76,18 +76,34 @@ am__nobase_list = $(am__nobase_strip_setup); \
 am__base_list = \
   sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
   sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
-am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(sbindir)"
+am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(sbindir)" \
+	"$(DESTDIR)$(man8dir)"
 LTLIBRARIES = $(lib_LTLIBRARIES)
-libxt_ACCOUNT_cl_la_LIBADD =
-libxt_ACCOUNT_cl_la_SOURCES = libxt_ACCOUNT_cl.c
-libxt_ACCOUNT_cl_la_OBJECTS = libxt_ACCOUNT_cl.lo
+am__DEPENDENCIES_1 =
+libipset_la_DEPENDENCIES = $(am__DEPENDENCIES_1)
+am__dirstamp = $(am__leading_dot)dirstamp
+am_libipset_la_OBJECTS = libipset/data.lo libipset/icmp.lo \
+	libipset/icmpv6.lo libipset/mnl.lo libipset/parse.lo \
+	libipset/print.lo libipset/session.lo libipset/types.lo
+libipset_la_OBJECTS = $(am_libipset_la_OBJECTS)
 AM_V_lt = $(am__v_lt_$(V))
 am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
 am__v_lt_0 = --silent
+libipset_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
+	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
+	$(libipset_la_LDFLAGS) $(LDFLAGS) -o $@
 PROGRAMS = $(sbin_PROGRAMS)
-iptaccount_SOURCES = iptaccount.c
-iptaccount_OBJECTS = iptaccount.$(OBJEXT)
-iptaccount_DEPENDENCIES = libxt_ACCOUNT_cl.la
+am_ipset_OBJECTS = src/ipset.$(OBJEXT) src/errcode.$(OBJEXT) \
+	src/ui.$(OBJEXT) src/ipset_bitmap_ip.$(OBJEXT) \
+	src/ipset_bitmap_ipmac.$(OBJEXT) \
+	src/ipset_bitmap_port.$(OBJEXT) src/ipset_hash_ip.$(OBJEXT) \
+	src/ipset_hash_ipport.$(OBJEXT) \
+	src/ipset_hash_ipportip.$(OBJEXT) \
+	src/ipset_hash_ipportnet.$(OBJEXT) \
+	src/ipset_hash_net.$(OBJEXT) src/ipset_hash_netport.$(OBJEXT) \
+	src/ipset_list_set.$(OBJEXT)
+ipset_OBJECTS = $(am_ipset_OBJECTS)
+ipset_DEPENDENCIES = libipset.la
 DEFAULT_INCLUDES = -I.@am__isrc@ -I$(top_builddir)
 depcomp = $(SHELL) $(top_srcdir)/depcomp
 am__depfiles_maybe = depfiles
@@ -114,8 +130,11 @@ am__v_CCLD_0 = @echo "  CCLD  " $@;
 AM_V_GEN = $(am__v_GEN_$(V))
 am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
 am__v_GEN_0 = @echo "  GEN   " $@;
-SOURCES = libxt_ACCOUNT_cl.c iptaccount.c
-DIST_SOURCES = libxt_ACCOUNT_cl.c iptaccount.c
+SOURCES = $(libipset_la_SOURCES) $(ipset_SOURCES)
+DIST_SOURCES = $(libipset_la_SOURCES) $(ipset_SOURCES)
+man8dir = $(mandir)/man8
+NROFF = nroff
+MANS = $(man_MANS)
 ETAGS = etags
 CTAGS = ctags
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
@@ -242,14 +261,28 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 xtlibdir = @xtlibdir@
-AM_CPPFLAGS = ${regular_CPPFLAGS} -I${abs_top_srcdir}/extensions
-AM_CFLAGS = ${regular_CFLAGS}
+AM_CPPFLAGS = -I${srcdir}/include -DNDEBUG
+AM_CFLAGS = ${regular_CFLAGS} ${libmnl_CFLAGS}
 XA_SRCDIR = ${srcdir}
 XA_TOPSRCDIR = ${top_srcdir}
 XA_ABSTOPSRCDIR = ${abs_top_srcdir}
 _mcall = -f ${top_builddir}/Makefile.iptrules
-iptaccount_LDADD = libxt_ACCOUNT_cl.la
-lib_LTLIBRARIES = libxt_ACCOUNT_cl.la
+lib_LTLIBRARIES = libipset.la
+libipset_la_SOURCES = libipset/data.c libipset/icmp.c libipset/icmpv6.c \
+                      libipset/mnl.c libipset/parse.c libipset/print.c \
+                      libipset/session.c libipset/types.c
+
+libipset_la_LIBADD = ${libmnl_LIBS}
+libipset_la_LDFLAGS = -version-info 1:0:0
+ipset_SOURCES = src/ipset.c src/errcode.c src/ui.c src/ipset_bitmap_ip.c \
+                src/ipset_bitmap_ipmac.c src/ipset_bitmap_port.c \
+                src/ipset_hash_ip.c src/ipset_hash_ipport.c \
+                src/ipset_hash_ipportip.c src/ipset_hash_ipportnet.c \
+                src/ipset_hash_net.c src/ipset_hash_netport.c \
+                src/ipset_list_set.c
+
+ipset_LDADD = libipset.la
+man_MANS = ipset.8
 all: all-am
 
 .SUFFIXES:
@@ -263,9 +296,9 @@ $(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/../../Makefile.extra $(a
 	      exit 1;; \
 	  esac; \
 	done; \
-	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign extensions/ACCOUNT/Makefile'; \
+	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign extensions/ipset-6/Makefile'; \
 	$(am__cd) $(top_srcdir) && \
-	  $(AUTOMAKE) --foreign extensions/ACCOUNT/Makefile
+	  $(AUTOMAKE) --foreign extensions/ipset-6/Makefile
 .PRECIOUS: Makefile
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	@case '$?' in \
@@ -315,8 +348,30 @@ clean-libLTLIBRARIES:
 	  echo "rm -f \"$${dir}/so_locations\""; \
 	  rm -f "$${dir}/so_locations"; \
 	done
-libxt_ACCOUNT_cl.la: $(libxt_ACCOUNT_cl_la_OBJECTS) $(libxt_ACCOUNT_cl_la_DEPENDENCIES) 
-	$(AM_V_CCLD)$(LINK) -rpath $(libdir) $(libxt_ACCOUNT_cl_la_OBJECTS) $(libxt_ACCOUNT_cl_la_LIBADD) $(LIBS)
+libipset/$(am__dirstamp):
+	@$(MKDIR_P) libipset
+	@: > libipset/$(am__dirstamp)
+libipset/$(DEPDIR)/$(am__dirstamp):
+	@$(MKDIR_P) libipset/$(DEPDIR)
+	@: > libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/data.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/icmp.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/icmpv6.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/mnl.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/parse.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/print.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/session.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset/types.lo: libipset/$(am__dirstamp) \
+	libipset/$(DEPDIR)/$(am__dirstamp)
+libipset.la: $(libipset_la_OBJECTS) $(libipset_la_DEPENDENCIES) 
+	$(AM_V_CCLD)$(libipset_la_LINK) -rpath $(libdir) $(libipset_la_OBJECTS) $(libipset_la_LIBADD) $(LIBS)
 install-sbinPROGRAMS: $(sbin_PROGRAMS)
 	@$(NORMAL_INSTALL)
 	test -z "$(sbindir)" || $(MKDIR_P) "$(DESTDIR)$(sbindir)"
@@ -360,18 +415,96 @@ clean-sbinPROGRAMS:
 	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
 	echo " rm -f" $$list; \
 	rm -f $$list
-iptaccount$(EXEEXT): $(iptaccount_OBJECTS) $(iptaccount_DEPENDENCIES) 
-	@rm -f iptaccount$(EXEEXT)
-	$(AM_V_CCLD)$(LINK) $(iptaccount_OBJECTS) $(iptaccount_LDADD) $(LIBS)
+src/$(am__dirstamp):
+	@$(MKDIR_P) src
+	@: > src/$(am__dirstamp)
+src/$(DEPDIR)/$(am__dirstamp):
+	@$(MKDIR_P) src/$(DEPDIR)
+	@: > src/$(DEPDIR)/$(am__dirstamp)
+src/ipset.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
+src/errcode.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ui.$(OBJEXT): src/$(am__dirstamp) src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_bitmap_ip.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_bitmap_ipmac.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_bitmap_port.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_hash_ip.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_hash_ipport.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_hash_ipportip.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_hash_ipportnet.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_hash_net.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_hash_netport.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+src/ipset_list_set.$(OBJEXT): src/$(am__dirstamp) \
+	src/$(DEPDIR)/$(am__dirstamp)
+ipset$(EXEEXT): $(ipset_OBJECTS) $(ipset_DEPENDENCIES) 
+	@rm -f ipset$(EXEEXT)
+	$(AM_V_CCLD)$(LINK) $(ipset_OBJECTS) $(ipset_LDADD) $(LIBS)
 
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT)
+	-rm -f libipset/data.$(OBJEXT)
+	-rm -f libipset/data.lo
+	-rm -f libipset/icmp.$(OBJEXT)
+	-rm -f libipset/icmp.lo
+	-rm -f libipset/icmpv6.$(OBJEXT)
+	-rm -f libipset/icmpv6.lo
+	-rm -f libipset/mnl.$(OBJEXT)
+	-rm -f libipset/mnl.lo
+	-rm -f libipset/parse.$(OBJEXT)
+	-rm -f libipset/parse.lo
+	-rm -f libipset/print.$(OBJEXT)
+	-rm -f libipset/print.lo
+	-rm -f libipset/session.$(OBJEXT)
+	-rm -f libipset/session.lo
+	-rm -f libipset/types.$(OBJEXT)
+	-rm -f libipset/types.lo
+	-rm -f src/errcode.$(OBJEXT)
+	-rm -f src/ipset.$(OBJEXT)
+	-rm -f src/ipset_bitmap_ip.$(OBJEXT)
+	-rm -f src/ipset_bitmap_ipmac.$(OBJEXT)
+	-rm -f src/ipset_bitmap_port.$(OBJEXT)
+	-rm -f src/ipset_hash_ip.$(OBJEXT)
+	-rm -f src/ipset_hash_ipport.$(OBJEXT)
+	-rm -f src/ipset_hash_ipportip.$(OBJEXT)
+	-rm -f src/ipset_hash_ipportnet.$(OBJEXT)
+	-rm -f src/ipset_hash_net.$(OBJEXT)
+	-rm -f src/ipset_hash_netport.$(OBJEXT)
+	-rm -f src/ipset_list_set.$(OBJEXT)
+	-rm -f src/ui.$(OBJEXT)
 
 distclean-compile:
 	-rm -f *.tab.c
 
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/iptaccount.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libxt_ACCOUNT_cl.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/data.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/icmp.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/icmpv6.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/mnl.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/parse.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/print.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/session.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@libipset/$(DEPDIR)/types.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/errcode.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_bitmap_ip.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_bitmap_ipmac.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_bitmap_port.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_hash_ip.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_hash_ipport.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_hash_ipportip.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_hash_ipportnet.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_hash_net.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_hash_netport.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ipset_list_set.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@src/$(DEPDIR)/ui.Po@am__quote@
 
 .c.o:
 @am__fastdepCC_TRUE@	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
@@ -405,6 +538,45 @@ mostlyclean-libtool:
 
 clean-libtool:
 	-rm -rf .libs _libs
+	-rm -rf libipset/.libs libipset/_libs
+install-man8: $(man_MANS)
+	@$(NORMAL_INSTALL)
+	test -z "$(man8dir)" || $(MKDIR_P) "$(DESTDIR)$(man8dir)"
+	@list=''; test -n "$(man8dir)" || exit 0; \
+	{ for i in $$list; do echo "$$i"; done; \
+	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
+	  sed -n '/\.8[a-z]*$$/p'; \
+	} | while read p; do \
+	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	  echo "$$d$$p"; echo "$$p"; \
+	done | \
+	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^8][0-9a-z]*$$,8,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
+	sed 'N;N;s,\n, ,g' | { \
+	list=; while read file base inst; do \
+	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
+	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man8dir)/$$inst'"; \
+	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man8dir)/$$inst" || exit $$?; \
+	  fi; \
+	done; \
+	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
+	while read files; do \
+	  test -z "$$files" || { \
+	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man8dir)'"; \
+	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man8dir)" || exit $$?; }; \
+	done; }
+
+uninstall-man8:
+	@$(NORMAL_UNINSTALL)
+	@list=''; test -n "$(man8dir)" || exit 0; \
+	files=`{ for i in $$list; do echo "$$i"; done; \
+	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
+	  sed -n '/\.8[a-z]*$$/p'; \
+	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^8][0-9a-z]*$$,8,;x' \
+	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
+	test -z "$$files" || { \
+	  echo " ( cd '$(DESTDIR)$(man8dir)' && rm -f" $$files ")"; \
+	  cd "$(DESTDIR)$(man8dir)" && rm -f $$files; }
 
 ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
 	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
@@ -459,6 +631,19 @@ distclean-tags:
 	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
 
 distdir: $(DISTFILES)
+	@list='$(MANS)'; if test -n "$$list"; then \
+	  list=`for p in $$list; do \
+	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
+	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
+	  if test -n "$$list" && \
+	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
+	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
+	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
+	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
+	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
+	    exit 1; \
+	  else :; fi; \
+	else :; fi
 	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
 	list='$(DISTFILES)'; \
@@ -490,9 +675,9 @@ distdir: $(DISTFILES)
 	done
 check-am: all-am
 check: check-am
-all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) all-local
+all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(MANS) all-local
 installdirs:
-	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(sbindir)"; do \
+	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(sbindir)" "$(DESTDIR)$(man8dir)"; do \
 	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
 	done
 install: install-am
@@ -516,6 +701,10 @@ clean-generic:
 distclean-generic:
 	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
 	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
+	-rm -f libipset/$(DEPDIR)/$(am__dirstamp)
+	-rm -f libipset/$(am__dirstamp)
+	-rm -f src/$(DEPDIR)/$(am__dirstamp)
+	-rm -f src/$(am__dirstamp)
 
 maintainer-clean-generic:
 	@echo "This command is intended for maintainers to use"
@@ -526,7 +715,7 @@ clean-am: clean-generic clean-libLTLIBRARIES clean-libtool clean-local \
 	clean-sbinPROGRAMS mostlyclean-am
 
 distclean: distclean-am
-	-rm -rf ./$(DEPDIR)
+	-rm -rf libipset/$(DEPDIR) src/$(DEPDIR)
 	-rm -f Makefile
 distclean-am: clean-am distclean-compile distclean-generic \
 	distclean-tags
@@ -543,7 +732,7 @@ info: info-am
 
 info-am:
 
-install-data-am:
+install-data-am: install-man
 
 install-dvi: install-dvi-am
 
@@ -560,7 +749,7 @@ install-info: install-info-am
 
 install-info-am:
 
-install-man:
+install-man: install-man8
 
 install-pdf: install-pdf-am
 
@@ -573,7 +762,7 @@ install-ps-am:
 installcheck-am:
 
 maintainer-clean: maintainer-clean-am
-	-rm -rf ./$(DEPDIR)
+	-rm -rf libipset/$(DEPDIR) src/$(DEPDIR)
 	-rm -f Makefile
 maintainer-clean-am: distclean-am maintainer-clean-generic
 
@@ -590,7 +779,10 @@ ps: ps-am
 
 ps-am:
 
-uninstall-am: uninstall-libLTLIBRARIES uninstall-sbinPROGRAMS
+uninstall-am: uninstall-libLTLIBRARIES uninstall-man \
+	uninstall-sbinPROGRAMS
+
+uninstall-man: uninstall-man8
 
 .MAKE: install-am install-strip
 
@@ -602,12 +794,13 @@ uninstall-am: uninstall-libLTLIBRARIES uninstall-sbinPROGRAMS
 	install-data install-data-am install-dvi install-dvi-am \
 	install-exec install-exec-am install-exec-local install-html \
 	install-html-am install-info install-info-am \
-	install-libLTLIBRARIES install-man install-pdf install-pdf-am \
-	install-ps install-ps-am install-sbinPROGRAMS install-strip \
-	installcheck installcheck-am installdirs maintainer-clean \
-	maintainer-clean-generic mostlyclean mostlyclean-compile \
-	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
-	tags uninstall uninstall-am uninstall-libLTLIBRARIES \
+	install-libLTLIBRARIES install-man install-man8 install-pdf \
+	install-pdf-am install-ps install-ps-am install-sbinPROGRAMS \
+	install-strip installcheck installcheck-am installdirs \
+	maintainer-clean maintainer-clean-generic mostlyclean \
+	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
+	pdf pdf-am ps ps-am tags uninstall uninstall-am \
+	uninstall-libLTLIBRARIES uninstall-man uninstall-man8 \
 	uninstall-sbinPROGRAMS
 
 
